import React from 'react';

export const themes = {
    default: {
        /* THIS THEME USES SPOTIFY'S COLOR AS ITS SECONDARY (2) */

        /* THE VERYSIMILAR GREEN HAS BEEN MODIFIED FROM THE GREEN IN THE URL BELOW */

        /* Palette URL: http://paletton.com/#uid=74E170kvvwqjjDVoCyMy5pdCOjQ */

        /* As hex codes */
        /* Main Primary color */
        colorPrimary0: "#6C0DAC",
        colorPrimary1: "#9654C2",
        colorPrimary2: "#7E31B2",
        colorPrimary3: "#530887",
        colorPrimary4: "#41056A",
        /* Main Secondary color (1) */
        colorSecondary10: "#FF3004",
        colorSecondary11: "#FF8065",
        colorSecondary12: "#FF5D3B",
        colorSecondary13: "#C92300",
        colorSecondary14: "#9E1B00",
        /* Main Secondary color (2) */
        colorSecondary20: "#1ED760",
        colorSecondary21: "#6FE89C",
        colorSecondary22: "#43DE7D",
        colorSecondary23: "#00D14E",
        colorSecondary24: "#009C3A",
        /* Main Complement color */
        colorComplement0: "#FFFA04",
        colorComplement1: "#FFFC65",
        colorComplement2: "#FFFB3B",
        colorComplement3: "#C9C500",
        colorComplement4: "#9E9B00",
        /* As RGBa codes */
        /* Main Primary color */
        rgbaPrimary0: "rgba(108, 13, 172, 1)",
        rgbaPrimary1: "rgba(150, 84, 194, 1)",
        rgbaPrimary2: "rgba(126, 49, 178, 1)",
        rgbaPrimary3: "rgba(83, 8, 135, 1)",
        rgbaPrimary4: "rgba(65, 5, 106, 1)",
        /* Main Secondary color (1) */
        rgbaSecondary10: "rgba(255, 48, 4, 1)",
        rgbaSecondary11: "rgba(255, 128, 101, 1)",
        rgbaSecondary12: "rgba(255, 93, 59, 1)",
        rgbaSecondary13: "rgba(201, 35, 0, 1)",
        rgbaSecondary14: "rgba(158, 27, 0, 1)",
        /* Main Secondary color (2) */
        rgbaSecondary20: "rgba(3, 186, 71, 1)",
        rgbaSecondary21: "rgba(81, 205, 127, 1)",
        rgbaSecondary22: "rgba(44, 191, 99, 1)",
        rgbaSecondary23: "rgba(0, 146, 54, 1)",
        rgbaSecondary24: "rgba(0, 115, 43, 1)",
        /* Main Complement color */
        rgbaComplement0: "rgba(255, 250, 4, 1)",
        rgbaComplement1: "rgba(255, 252, 101, 1)",
        rgbaComplement2: "rgba(255, 251, 59, 1)",
        rgbaComplement3: "rgba(201, 197, 0, 1)",
        rgbaComplement4: "rgba(158, 155, 0, 1)"

        /* Generated by Paletton.com © 2002 - 2014 */

        /* http://paletton.com */

    },
    alternate: {
        /* THIS THEME USES SPOTIFY'S COLOR AS ITS PRIMARY */

        /* Palette URL: http://paletton.com/#uid=72X170kryIIgFQrmlM7CfFKDMr4 */

        /* As hex codes */
        /* Main Primary color */
        colorPrimary0: "#1ED760",
        colorPrimary1: "#6FE89C",
        colorPrimary2: "#43DE7D",
        colorPrimary3: "#00D14E",
        colorPrimary4: "#009C3A",
        /* Main Secondary color (1) */
        colorSecondary10: "#4237D3",
        colorSecondary11: "#867FE5",
        colorSecondary12: "#6157DB",
        colorSecondary13: "#2316CC",
        colorSecondary14: "#190F96",
        /* Main Secondary color (2) */
        colorSecondary20: "#FFCD24",
        colorSecondary21: "#FFE17A",
        colorSecondary22: "#FFD64D",
        colorSecondary23: "#FFC500",
        colorSecondary24: "#D8A600",
        /* Main Complement color */
        colorComplement0: "#FF4A24",
        colorComplement1: "#FF917A",
        colorComplement2: "#FF6C4D",
        colorComplement3: "#FF2C00",
        colorComplement4: "#D82500",
        /* As RGBa codes */
        /* Main Primary color */
        rgbaPrimary0: "rgba(30, 215, 99, 1)",
        rgbaPrimary1: "rgba(111, 232, 156, 1)",
        rgbaPrimary2: "rgba(67, 222, 125, 1)",
        rgbaPrimary3: "rgba(0, 209, 78, 1)",
        rgbaPrimary4: "rgba(0, 156, 58, 1)",
        /* Main Secondary color (1) */
        rgbaSecondary10: "rgba(66, 55, 211, 1)",
        rgbaSecondary11: "rgba(134, 127, 229, 1)",
        rgbaSecondary12: "rgba(97, 87, 219, 1)",
        rgbaSecondary13: "rgba(35, 22, 204, 1)",
        rgbaSecondary14: "rgba(25, 15, 150, 1)",
        /* Main Secondary color (2) */
        rgbaSecondary20: "rgba(255, 205, 36, 1)",
        rgbaSecondary21: "rgba(255, 225, 122, 1)",
        rgbaSecondary22: "rgba(255, 214, 77, 1)",
        rgbaSecondary23: "rgba(255, 197, 0, 1)",
        rgbaSecondary24: "rgba(216, 166, 0, 1)",
        /* Main Complement color */
        rgbaComplement0: "rgba(255, 74, 36, 1)",
        rgbaComplement1: "rgba(255, 145, 122, 1)",
        rgbaComplement2: "rgba(255, 108, 77, 1)",
        rgbaComplement3: "rgba(255, 44, 0, 1)",
        rgbaComplement4: "rgba(216, 37, 0, 1)"

        /* Generated by Paletton.com © 2002 - 2014 */

        /* http://paletton.com */
    },
};

export const ThemeContext = React.createContext(themes.default);